# Override Fedora default grimshot bindings with grim+slurp+swappy
bindsym {
    Print       exec grim - | swappy -f -
    Alt+Print   exec grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | swappy -f -
    Ctrl+Print  exec grim -g "$(slurp)" - | swappy -f -
}
