# Override Fedora default grimshot bindings with grim+slurp+swappy
bindsym {
    Print       exec sh -c 'grim - | swappy -f -; notify-send "Screenshot saved" -t 2000'
    Alt+Print   exec sh -c 'grim -g "$(swaymsg -t get_tree | jq -r '"'"'.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'"'"')" - | swappy -f -; notify-send "Screenshot saved" -t 2000'
    Ctrl+Print  exec sh -c 'grim -g "$(slurp)" - | swappy -f -; notify-send "Screenshot saved" -t 2000'
}
